### ISSUE TITLE
Adding fields to message data

### ISSUE THREAD

**Issue by gerritholl** [pytroll/pytroll-watchers#42]
In our trollstalker processing, we add fields to the messages using configuration entries such as `var_platform_name=NOAA-20` or `var_orbit_number=0000`.  This was necessary for a reason I don't remember.  For a migration from trollstalker to pytroll-watchers, we would probably need this capability in pytroll-watchers as well, or a different solution to the same problem.

**Comment by mraspaud** [comment]
This should already be possible by providing the message config with some static info like this:
```yaml
...
message_config:
  subject: /segment/viirs/l1b/
  atype: file
  data:
    sensor: viirs
    var_platform_name: NOAA-20
    var_orbit_number: 0000
```
