### ISSUE TITLE
Improve documentation adding example on how to configure for watching for data in EUM Data Store

### ISSUE THREAD

**Issue by adybbroe** [pytroll/pytroll-watchers#46]
I am missing an example config on how I would use the watcher to look for new data in the EUMETSAT Data Store, here:
https://pytroll-watchers.readthedocs.io/en/latest/backends.html#module-pytroll_watchers.datastore_watcher

So, with some help I have created this yaml config file that works for my case:
```
backend: datastore
fs_config:
  search_params:
    collection: "EO:EUM:DAT:0905"
  polling_interval:
    minutes: 5
  start_from:
    hours: 6
  ds_auth:
    netrc_host: api.eumetsat.int

publisher_config:
  name: <my watcher publisher name>
  nameservers: false
  port: <my port number>
message_config:
  subject: /my/datastore/watcher/topic
  atype: file
  data:
    sensor: aws
    platform_name: AWS1
    variant: GDS
```
